server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipt?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: reciptuser
    password: recipereceipt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect