server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://192.168.0.4:3306/reciptMember?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: reciptuser
    password: recipereceipt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        create_empty_composites:
          enabled: true

  redis:
    port: 6379
    host: 192.168.0.4
    password: recipereceipt
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2


security:
  jwt:
    access:
      validate-time: 1800
      key: recipt-access
      algorithm: HS256
    refresh:
      validate-time: 7
      key: recipt-refresh
      algorithm: HS512
