server:
  port: 9010

spring:
  profiles:
    active: local

security:
  jwt:
    access:
      validate-time: 1800
      key: recipt-access
      algorithm: HS256
    refresh:
      validate-time: 7
      key: recipt-refresh
      algorithm: HS512
